import { readFileSync, writeFileSync } from 'fs';

const CSS_FILES = [
    // Core tokens used by Base Views UI
    'styles/variables.css',

    // Views used by current Base Views features
    'styles/bases-views.css'
];

const MAIN_CSS_TEMPLATE = `/* Base Views Plugin Styles */

/* 
   This file is automatically generated by the build process.
   To modify styles, edit the source files in the styles/ directory.
   
   Source files:
   
   Core:
   - styles/variables.css

   Views:
   - styles/bases-views.css
   
   Run 'npm run build-css' to regenerate this file.
*/

`;

const REMAINING_STYLES = ``;

function buildCSS() {
    console.log('Building CSS...');
    
    let combinedCSS = MAIN_CSS_TEMPLATE;
    
    // Read and concatenate each CSS file
    for (const cssFile of CSS_FILES) {
        try {
            const content = readFileSync(cssFile, 'utf8');
            
            // Add a section header comment
            const filename = cssFile.split('/').pop();
            combinedCSS += `\n/* ===== ${filename.toUpperCase()} ===== */\n`;
            combinedCSS += content;
            combinedCSS += '\n';
            
            console.log(`[OK] Included ${cssFile}`);
        } catch (error) {
            console.error(`[ERROR] Error reading ${cssFile}:`, error.message);
            process.exit(1);
        }
    }
    
    // Add the remaining modal styles
    combinedCSS += REMAINING_STYLES;
    
    // Write the combined CSS to styles.css
    try {
        writeFileSync('styles.css', combinedCSS);
        console.log('[OK] Built styles.css successfully');
        
        // Count lines for reference
        const lineCount = combinedCSS.split('\n').length;
        console.log(`[OK] Generated ${lineCount} lines of CSS`);
        
    } catch (error) {
        console.error('[ERROR] Error writing styles.css:', error.message);
        process.exit(1);
    }
}

// Run the build
buildCSS();
